### ISSUE TITLE
Assignment 1 - Ready for Review

### ISSUE THREAD

**Issue by a-lesser** [SES-5215-F2020/alesser-quant#1]
Hi Carol,

I am submitting the first assignment and have uploaded the Rmd and html files. I look forward to reviewing it with you. 

Best,
Aron

**Comment by c-voulgaris** [comment]
This is excellent. Since you submitted it early, I'd like to give some feedback so you have a chance to revise it slightly before making a final submission (I'll clarify these points in class tomorrow as well).

For full credit, you need to explicitly indicate:

1. Which variables you are using (you've done this)
2. Who is included in your sample (you could be more clear on this - you seem to indicate that your sample is renters of Hispanic origin in Georgia, but I don't think you've actually filtered on Hispanic origin - I think your sample is just all renters in Georgia)
3. What is your unit of analysis? Do the rows in your data represent people or households?
4. The number of observations in your dataset. 

You could meet the last two requirements by just adding a sentence that says "This dataset includes 25,856 individuals."

**Comment by a-lesser** [comment]
Thank you for your feedback and for giving me the chance to alter the submission. I will share a revision shortly. 

I do have one question - In the sample I include all documented renters in Georgia. Although I am interested in renters of Hispanic origin, I included all documented renters in Georgia in case I decide to look at Hispanic tenants in relation to non-Hispanic ones. However, if it will be difficult to filter by ethnicity later on, or if this may lead to an overly broad research question, then I can filter right now and not compare Hispanic and non-Hispanic renters. 

Would you suggest I choose the more specific demographic rather than considering a sample of all renters in GA?
